export class CommonConstants{
  static readonly FULL_PERCENT = "100%";
  static readonly HALF_PERCENT = "50%";
  static readonly EIGHTY_PERCENT = "80%";
  static readonly ADSORPTION_THRESHOLD = "18%";
  static readonly TOOL_BOX_BACKGROUND_COLOR = 0x808080;
  static readonly TOOL_BOX_OPACITY = 0.4;
  static readonly COMPONENT_SIZE: number = 0.5;
  static readonly INTERVAL_BETWEEN_COMPONENTS: number = 0.3;
  static readonly LEFT_PADDING: number = 0.8;
  static readonly ANIMATION_DURATION = 240;
  static readonly TOOL_ITEM_HEIGHT = 40;
  static readonly MAXIMUM_DISTANCE = 60;
  static readonly MAXIMUM_TOOLS= 6;
  static readonly LAYOUT_SPAN_DEG=180;

}